Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"

  config.vm.provision "shell", inline: <<-SH
yum update -y
  SH

  config.vm.provision "chef_solo" do |chef|
    # AMQP 0-9-1, AMQP 1.0
    config.vm.network "forwarded_port", guest: 5672,  host: 5692
    # HTTP API, management UI
    config.vm.network "forwarded_port", guest: 15672, host: 15692
    # MQTT
    config.vm.network "forwarded_port", guest: 1883,  host: 1897
    # STOMP
    config.vm.network "forwarded_port", guest: 61613, host: 61627

    chef.add_recipe "rabbitmq::erlang_package"
    chef.add_recipe "rabbitmq::default"
    chef.add_recipe "rabbitmq::mgmt_console"
    chef.add_recipe "rabbitmq::plugin_management"
    chef.add_recipe "rabbitmq::systemd_limits"

    # config.vm.synced_folder "/path/to/tls-gen/basic/result/",
    #                         "/vagrant/tls-gen"

    chef.json = {
      "rabbitmq": {
        "version": "3.7.15",

        "erlang": {
          "enabled": true
        },

        # See https://www.rabbitmq.com/production-checklist.html#resource-limits-file-handle-limit for details.
        "systemd": {
          "limits": {
            "NOFILE": 400_000
          }
        },

        # only to allow guest/guest logins via the forwarded port,
        # the right thing to do for production environments is delete
        # "guest" and create a new user account with a generated password.
        "loopback_users": [],
        "enabled_plugins": %w(rabbitmq_management rabbitmq_stomp rabbitmq_mqtt rabbitmq_amqp1_0)
      }
    }
  end
end
